# -*- coding: utf-8 -*-
"""app1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xs--UkZGhd5gUAp62JIxFu4nCB8Ojo4l
"""



import pandas as pd
import numpy as np
import pickle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

train_data = pd.read_csv("Titanic_train.csv")

features = ["Pclass", "Sex", "Age", "SibSp", "Parch", "Fare"]
train_data["Sex"] = train_data["Sex"].map({"male": 1, "female": 0})
train_data = train_data.dropna()

X = train_data[features]
y = train_data["Survived"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
model = LogisticRegression()
model.fit(X_train_scaled, y_train)
with open("model.pkl", "wb") as model_file:
    pickle.dump(model, model_file)
with open("preprocessor.pkl", "wb") as preprocessor_file:
    pickle.dump(scaler, preprocessor_file)

print("Model and scaler saved successfully!")
